groups:
  - name: Digital Equipo DOWN
    rules:
    - record: job:Node_Exporter_DIG:Status
      expr: up{job="CotoDigital"}

    - alert: NodeExporterDownDIG
      expr: job:Node_Exporter_DIG:Status == 0
      for: 2m
      annotations:
        summary: "Node Exporter is DOWN"
        description: "Node Exporter del {{ $labels.instance }} esta caido por mas de 2 min."


  - name: Digital Espacio Libre 
    rules:
    - record: job:FreeDiskSpace_DIG:Status
      expr: round((sum by (instance,job) (node_filesystem_free_bytes{job="CotoDigital"}) / sum by (instance,job) (node_filesystem_size_bytes{job="CotoDigital"})) * 100,0.1) 

    - alert: (DIG) Free Disk Space Warning
      expr: job:FreeDiskSpace_DIG:Status < 20
      for: 2m
      annotations:
        summary: "El Espacio libre en disco es Warning"
        description: "El disco se está llenando (quedan < 20%). El espacio libre actual del disco es {{ $value }}"


  - name: Digital Uso de FileSystem
    rules:
    - record: job:node_FileSystem_DIG:available
      expr: round((node_filesystem_size_bytes{job="CotoDigital",fstype=~"ext.*|xfs",mountpoint !~".*pod.*"}-node_filesystem_free_bytes{job="CotoDigital",fstype=~"ext.*|xfs",mountpoint !~".*pod.*"}) *100/(node_filesystem_avail_bytes {job="CotoDigital",fstype=~"ext.*|xfs",mountpoint !~".*pod.*"}+(node_filesystem_size_bytes{job="CotoDigital",fstype=~"ext.*|xfs",mountpoint !~".*pod.*"}-node_filesystem_free_bytes{job="CotoDigital",fstype=~"ext.*|xfs",mountpoint !~".*pod.*"})),0.1) 

    - alert: (DIG) FileSystem Warning
      expr: 85 < (job:node_FileSystem_DIG:available) < 90
      for: 2m
      annotations:
        summary: "Uso de FileSystem: Warning"
        description: "FileSystem {{ $labels.mountpoint }} de {{ $labels.instance }} valor actual {{ $value }}% supera el 85%."

    - alert: (DIG) FileSystem Critical
      expr: (job:node_FileSystem_DIG:available) >= 90
      for: 2m
      annotations:
        summary: "Uso de FileSystem: CRITICAL"
        description: "FileSystem {{ $labels.mountpoint }} de {{ $labels.instance }} valor actual {{ $value }}% supera el 90%."


  - name: Digital Uso de RAM
    rules:
    - record: job:node_memory_Mem_bytes_DIG:available
      expr: round(100 - ((node_memory_MemAvailable_bytes{job="CotoDigital"} / node_memory_MemTotal_bytes{job="CotoDigital"}) * 100),0.1) 

    - alert: (DIG) Memoria Usada Warning
      expr: 70 < (job:node_memory_Mem_bytes_DIG:available) < 85
      for: 2m
      annotations:
        summary: "Memoria usada es WARNING"
        description: "Memoria de host {{ $labels.instance }} valor actual {{ $value }}% supera el 70%."

    - alert: (DIG) Memoria usada Critical
      expr: (job:node_memory_Mem_bytes_DIG:available) >= 85
      for: 2m
      annotations:
        summary: "Memoria usada is CRITICAL"
        description: "Memoria de host {{ $labels.instance }} valor actual {{ $value }}% supera el 85%."


  - name: Digital Uso de CPU
    rules:
    - record: job:USO_CPU_DIG:available
      expr: round((1 - avg(rate(node_cpu_seconds_total{job="CotoDigital",mode="idle"}[5m])) by (instance,job)) * 100,0.1)

    - alert: (DIG) Uso de CPU Critical
      expr: (job:USO_CPU_DIG:available) >= 90
      for: 2m
      annotations:
        summary: "Uso de CPU: Critical"
        description: "Uso de CPU en host {{ $labels.instance }} valor actual {{ $value }}% supera el 85%."

